"""Ported command registry for the Python porting workspace."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class CommandEntry:
    name: str
    description: str = ""
    plugin: bool = False

    def execute(self, prompt: str) -> str:
        return f"Mirrored command '{self.name}': {prompt}"


def _cmd(name: str, description: str = "", plugin: bool = False) -> CommandEntry:
    return CommandEntry(name=name, description=description, plugin=plugin)


PORTED_COMMANDS: list[CommandEntry] = [
    _cmd("review", "Code review command"),
    _cmd("analyze", "Analyze code or data"),
    _cmd("summarize", "Summarize content"),
    _cmd("explain", "Explain code or concepts"),
    _cmd("document", "Generate documentation"),
    _cmd("refactor", "Refactor code"),
    _cmd("test", "Run tests"),
    _cmd("debug", "Debug code"),
    _cmd("lint", "Lint code"),
    _cmd("format", "Format code"),
    _cmd("search", "Search codebase"),
    _cmd("find", "Find files or symbols"),
    _cmd("create", "Create resources"),
    _cmd("update", "Update resources"),
    _cmd("delete", "Delete resources"),
    _cmd("list", "List resources"),
    _cmd("show", "Show details"),
    _cmd("run", "Run a command"),
    _cmd("execute", "Execute code"),
    _cmd("build", "Build the project"),
    _cmd("deploy", "Deploy project"),
    _cmd("check", "Check status"),
    _cmd("validate", "Validate inputs"),
    _cmd("audit", "Audit codebase"),
    _cmd("scan", "Scan for issues"),
    _cmd("profile", "Profile performance"),
    _cmd("benchmark", "Benchmark code"),
    _cmd("inspect", "Inspect objects"),
    _cmd("trace", "Trace execution"),
    _cmd("monitor", "Monitor services"),
    _cmd("log", "Log output"),
    _cmd("report", "Generate report"),
    _cmd("generate", "Generate code"),
    _cmd("describe", "Describe resources"),
    _cmd("diff", "Show diff"),
    _cmd("compare", "Compare files"),
    _cmd("merge", "Merge branches"),
    _cmd("rebase", "Rebase branch"),
    _cmd("commit", "Commit changes"),
    _cmd("push", "Push changes"),
    _cmd("pull", "Pull changes"),
    _cmd("clone", "Clone repository"),
    _cmd("init", "Initialize project"),
    _cmd("install", "Install dependencies"),
    _cmd("uninstall", "Uninstall package"),
    _cmd("upgrade", "Upgrade package"),
    _cmd("rollback", "Rollback changes"),
    _cmd("migrate", "Migrate data"),
    _cmd("backup", "Backup data"),
    _cmd("restore", "Restore data"),
    _cmd("export", "Export data"),
    _cmd("import-data", "Import data"),
    _cmd("convert", "Convert formats"),
    _cmd("transform", "Transform data"),
    _cmd("encode", "Encode data"),
    _cmd("decode", "Decode data"),
    _cmd("encrypt", "Encrypt data"),
    _cmd("decrypt", "Decrypt data"),
    _cmd("sign", "Sign artifacts"),
    _cmd("verify", "Verify signatures"),
    _cmd("publish", "Publish packages"),
    _cmd("subscribe", "Subscribe to events"),
    _cmd("connect", "Connect to service"),
    _cmd("disconnect", "Disconnect from service"),
    _cmd("auth", "Authenticate"),
    _cmd("login", "Login to service"),
    _cmd("logout", "Logout from service"),
    _cmd("register", "Register resource"),
    _cmd("reset", "Reset state"),
    _cmd("configure", "Configure settings"),
    _cmd("setup", "Setup environment"),
    _cmd("teardown", "Teardown environment"),
    _cmd("start", "Start service"),
    _cmd("stop", "Stop service"),
    _cmd("restart", "Restart service"),
    _cmd("reload", "Reload configuration"),
    _cmd("pause", "Pause operation"),
    _cmd("resume", "Resume operation"),
    _cmd("cancel", "Cancel operation"),
    _cmd("queue", "Queue operation"),
    _cmd("schedule", "Schedule operation"),
    _cmd("trigger", "Trigger event"),
    _cmd("notify", "Send notification"),
    _cmd("alert", "Send alert"),
    _cmd("send", "Send message"),
    _cmd("receive", "Receive message"),
    _cmd("fetch", "Fetch resource"),
    _cmd("post", "Post resource"),
    _cmd("get-resource", "Get resource"),
    _cmd("put-resource", "Put resource"),
    _cmd("patch-resource", "Patch resource"),
    _cmd("delete-resource", "Delete resource"),
    _cmd("stream", "Stream data"),
    _cmd("pipe", "Pipe data"),
    _cmd("filter", "Filter data"),
    _cmd("sort", "Sort data"),
    _cmd("aggregate", "Aggregate data"),
    _cmd("group-by", "Group data"),
    _cmd("join", "Join datasets"),
    _cmd("split", "Split data"),
    _cmd("zip-files", "Zip files"),
    _cmd("unzip-files", "Unzip files"),
    _cmd("archive", "Archive files"),
    _cmd("extract", "Extract archive"),
    _cmd("compress", "Compress data"),
    _cmd("decompress", "Decompress data"),
    _cmd("hash-file", "Hash file"),
    _cmd("checksum", "Compute checksum"),
    _cmd("diff-file", "Diff files"),
    _cmd("patch-file", "Patch file"),
    _cmd("apply", "Apply changes"),
    _cmd("revert", "Revert changes"),
    _cmd("save", "Save data"),
    _cmd("load", "Load data"),
    _cmd("open-file", "Open file"),
    _cmd("close-file", "Close file"),
    _cmd("read-file", "Read file"),
    _cmd("write-file", "Write file"),
    _cmd("append-file", "Append to file"),
    _cmd("replace-text", "Replace text"),
    _cmd("insert-text", "Insert text"),
    _cmd("remove-text", "Remove text"),
    _cmd("clear-cache", "Clear cache"),
    _cmd("flush-cache", "Flush cache"),
    _cmd("sync", "Sync data"),
    _cmd("cache", "Cache data"),
    _cmd("invalidate", "Invalidate cache"),
    _cmd("preload", "Preload data"),
    _cmd("prefetch", "Prefetch data"),
    _cmd("warmup", "Warmup service"),
    _cmd("health-check", "Health check"),
    _cmd("ping", "Ping service"),
    _cmd("version-check", "Check version"),
    _cmd("security-scan", "Security scan"),
    _cmd("vulnerability-scan", "Vulnerability scan"),
    _cmd("license-check", "License check"),
    _cmd("compliance-check", "Compliance check"),
    _cmd("code-review", "Code review"),
    _cmd("peer-review", "Peer review"),
    _cmd("automated-review", "Automated review"),
    _cmd("static-analysis", "Static analysis"),
    _cmd("dynamic-analysis", "Dynamic analysis"),
    _cmd("fuzzing", "Fuzzing"),
    _cmd("unit-test", "Unit test"),
    _cmd("integration-test", "Integration test"),
    _cmd("end-to-end-test", "End-to-end test"),
    _cmd("smoke-test", "Smoke test"),
    _cmd("regression-test", "Regression test"),
    _cmd("performance-test", "Performance test"),
    _cmd("load-test", "Load test"),
    _cmd("stress-test", "Stress test"),
    _cmd("contract-test", "Contract test"),
    _cmd("snapshot-test", "Snapshot test"),
    _cmd("visual-test", "Visual test"),
    _cmd("accessibility-test", "Accessibility test"),
    _cmd("security-test", "Security test"),
    _cmd("penetration-test", "Penetration test"),
    _cmd("code-coverage", "Code coverage"),
    _cmd("documentation-check", "Documentation check"),
    _cmd("dependency-update", "Update dependencies"),
    _cmd("dependency-audit", "Audit dependencies"),
    _cmd("plugin-install", "Install plugin", plugin=True),
    _cmd("plugin-uninstall", "Uninstall plugin", plugin=True),
    _cmd("plugin-list", "List plugins", plugin=True),
    _cmd("plugin-enable", "Enable plugin", plugin=True),
    _cmd("plugin-disable", "Disable plugin", plugin=True),
    _cmd("workspace-init", "Initialize workspace"),
    _cmd("workspace-status", "Workspace status"),
    _cmd("workspace-clean", "Clean workspace"),
    _cmd("workspace-reset", "Reset workspace"),
    _cmd("workspace-sync", "Sync workspace"),
    _cmd("session-start", "Start session"),
    _cmd("session-end", "End session"),
    _cmd("session-list", "List sessions"),
    _cmd("session-resume", "Resume session"),
    _cmd("session-export", "Export session"),
    _cmd("mcp-connect", "Connect MCP server"),
    _cmd("mcp-disconnect", "Disconnect MCP server"),
    _cmd("mcp-list", "List MCP resources"),
    _cmd("mcp-call", "Call MCP tool"),
    _cmd("mcp-status", "MCP server status"),
    _cmd("token-count", "Count tokens"),
    _cmd("context-window", "Show context window"),
    _cmd("model-info", "Show model info"),
    _cmd("temperature-set", "Set temperature"),
    _cmd("system-prompt", "Set system prompt"),
]

if len(PORTED_COMMANDS) < 150:
    raise RuntimeError(f"Expected >= 150 commands, got {len(PORTED_COMMANDS)}")
